services:
  postgres:
    image: pgvector/pgvector:0.8.6-pg18-trixie
    container_name: vidscribe-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: